NSABP_POC/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NSABP_Model_BO_;
using System.Data;
using NSABP_BLL;


namespace NSABP.Controllers
{
    public class ConfigurationController : Controller
    {
        // GET: Configuration
        [HttpGet]
        public ActionResult Protocol_Form_Config()
        {
            try
            {
                load_dropdowns();
               
            }
            catch (Exception ex)
            {

                
            }
            return View(Configuration_BLL.GetForms());
        }

        //public ActionResult Protocol_Form_Config(IEnumerable<checkboxes_BO> bo, FormCollection form)
        //{
        //    try
        //    {
        //        load_dropdowns();
        //        if (form["forms"] != null)
        //        {
        //            string[] selected_FormIDS = form["forms"].Split(',');
        //            int protocol_Id = Convert.ToInt16(form["Protocol"]);

        //               if( Configuration_BLL.Config_Protocol_form(protocol_Id, selected_FormIDS))
        //            {
        //                ViewBag.Message = "Forms Configured successfully";
        //            }

        //            ViewBag.SelectedItem = protocol_Id;
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Please select at least one form ";
        //        }

        //    }
        //    catch (Exception ex)
        //    {


        //    }
        //    return View(Configuration_BLL.GetForms());

        //}
        [HttpPost]
        public ActionResult Protocol_Form_Config(List<checkboxes_BO> bo)
        {

            try
            {
                if (Configuration_BLL.Config_Protocol_form_Timepoint(bo))
                {


                    return Json(new { Message = "Success" });

                }
                else
                {
                    return Json(new { Message = "Invalid" });
                }
            }
            catch (Exception ex)
            {
            }
            return Json(new { Message = "Invalid" });
        }

        public ActionResult form_chechboxList(int protocol_ID)
        {
            try
            {

                List<int> list_IDs = Configuration_BLL.GetForms_IDS(protocol_ID);
                var list = Configuration_BLL.GetForms().ToList();
                List<checkboxes_BO> res = new List<checkboxes_BO>();
                //changes start TimepointConfiguration
                //foreach (checkboxes_BO bo in list)
                //{
                //    if (list_IDs.Contains(bo.ID))
                //        bo._isChecked = true;
                //    else
                //        bo._isChecked = false;
                //    res.Add(bo);
                //}

                //return PartialView("form_chechboxList", res);

                DataTable dt = Configuration_BLL.GetForms_TimePoints(protocol_ID);
                foreach (checkboxes_BO bo in list)
                {
                    if (dt.Select("T7_FormID =" + bo.ID + "").Count() > 0)
                    {
                        bo._isChecked = true;
                        bo.StrArray = dt.AsEnumerable().Where
                (row => row.Field<int>("T7_FormID") == bo.ID)
                    .Select(s => s.Field<string>("TimePoint"))
                    //.Distinct()
                    .ToList();
                        //    bo.StrArray = dt.Select("T7_FormID = " + bo.ID + "")[0][]

                    }
                    else
                        bo._isChecked = false;
                    res.Add(bo);
                }
                return Json(new { result = res });
            }
            catch (Exception ex)
            {
            }

            return Json(new { result = "Invalid" });

        }


        public void load_dropdowns()
        {
            try
            {
                DataSet ds = new DataSet();
                ds = User_BLL.GetProtocols_Roles_Status();
                DataTable dtprotcol = ds.Tables[0];
              //  ViewBag.Protocol = new SelectList(dtprotcol.AsDataView(), "Id", "Protocol_Code");
                ViewBag.Protocol = new SelectList(User_BLL.GetProtocols().AsDataView(), "Id", "Protocol_Code");
                DataTable dt = ds.Tables[1];
                ViewBag.Role = new SelectList(dt.AsDataView(), "ID", "Role_Name");
              
                //ViewBag.Protocol = new SelectList(User_BLL.GetProtocols().AsDataView(), "Id", "Protocol_Code");

            }
            catch (Exception)
            {

                throw;
            }


        }



    }
}

NSABP_POC/Views/Configuration/Protocol_Form_Config.cshtml
@model List<NSABP_Model_BO_.checkboxes_BO>
@{
    ViewBag.Title = "Protocol Form Configuration";
    Layout = "~/Views/Shared/_LayoutPage_ADMIN.cshtml";
}

@*@using (Html.BeginForm("Protocol_Form_Config", "Configuration", FormMethod.Post))
    {*@
@Html.AntiForgeryToken()
<div class="card-body col-xl-8">
    <div class="form-group row">
        @Html.Label("Protocol", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4 dropdown ">
            @Html.DropDownList("Protocol", ViewBag.Protocol as SelectList, "-Select-", new { @class = " form-control" })
            @Html.ValidationMessage("Protocol", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group row">
            @Html.Label("Roles", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4 dropdown ">
                @Html.DropDownList("Role", ViewBag.Role as SelectList, "-Select-", new { @class = " form-control" })
                @Html.ValidationMessage("Role", new { @class = "text-danger" })
            </div>
        </div>*@
    <div class="form-group row  ">
        @Html.Label("Form Name", htmlAttributes: new { @class = "control-label col-md-2 " })
        <div class="col-md-10">
            <div id="div_check_form">
                @*@Html.Partial("form_chechboxList", Model)*@
                @{
                    //for (int i = 0; i < Model.Count(); i++)
                    foreach (var i in Model)
                    {

                        <div class="row" id="chkdiv_@i">

                            @*@Html.CheckBoxFor(it => it[i]._isChecked, new { Style = "vertical-align:3px}" })*@
                            <input type="checkbox" class="chk" checked=@i._isChecked name="forms" id=chk_@i.ID value="@i.ID" onclick="checkoruncheck(this)" />
                            <div class="col-md-4">
                                @Html.HiddenFor(it => i.ID)
                                @Html.DisplayFor(it => i.Name)
                            </div>
                            No.Of TimePoints
                            <div class="col-md-5">
                                <input type="text" id="txt_@i.ID" class="form-control col-md-4 clsTPCount" onchange="createTimeponts(this);" onkeypress="return AllowOnlyNumbers(event);" disabled />
                            </div>
                        </div>


                    }
                }
            </div>
        </div>
    </div>
    <div class="form-group row ">
        <input type="button" value="Configure" class="btn btn-info" id="btnConfigure" />
    </div>
</div>

<script type="text/javascript">
            $('#Protocol').change(function () {
                $('input:checkbox').prop('checked',false);
                $('input:text').val('').attr('disabled','disabled');
                $(".clsTimepoints").parent().remove();
                var obj;
                var protocol_id1 = $(this).val();
                if (protocol_id1 != "") {
                    var url = "/Configuration/form_chechboxlist?protocol_ID=" + protocol_id1;
                   // var url = "/Configuration/Protocol_Form_Config?protocol_ID=" + protocol_id1;
                   // $('#div_check_form').load(url);
                    $.post(url,  function (Data) {

                        obj = Data.result;

                        for (var i = 0; i < obj.length; i++)
                        {
                            debugger;
                            var chk = $("#chk_" + obj[i].ID + "");
                            chk.prop("checked", obj[i]._isChecked);
                           // chk.val(chk.prop('checked'));
                            //alert(obj[i]._isChecked);
                            $("#chk_" + obj[i].ID + "").attr("checked", obj[i]._isChecked);
                            //changed
                            var txt = $("#txt_" + obj[i].ID + "");
                            $("#txt_" + obj[i].ID + "").removeAttr('disabled');
                            if (obj[i].StrArray != null) {
                                txt.val(obj[i].StrArray.length);
                                //for create tiem points based on time point count
                                if (txt.val() > 1) {//condition for value of time point must greater than 1
                                    createTimeponts(txt);
                                    var j = 0;
                                    debugger;
                                    //for assign time points
                                    $("#txt_" + obj[i].ID + "").parent().next().find(".clsTimepoints").each(function () {
                                        $(this).val(obj[i].StrArray[j]);

                                        j++;

                                    });
                                    j = 0;
                                }
                            }
                            else
                                txt.val('').attr('disabled','disabled');


                            //chnages end
                        }

                    })
                }
                else
                {
                    debugger;
                    $('input:checkbox').prop('checked',false);
                    $('input:text').val('').attr('disabled');
                    $(".clsTimepoints").parent().remove();
                }
            });
            function checkoruncheck(id)
            {
                debugger;
                if (($(id).prop("checked") == false)) {
                    $(id).next('div').next('div').find('input:text').val('');

                    $(id).next('div').next('div').next('div').remove();
                    $(id).next('div').next('div').find('input:text').attr('disabled', 'disbled');
                }
                else
                {
                    $(id).next('div').next('div').find('input:text').removeAttr('disabled').focus().val('1');

                }
            }
</script>
<script>
    function createTimeponts(id)
    {
        var txtval = $(id).val();

        if (txtval == "")
        {
            $(id).parent().next().remove();
            alert('Please enter no.of Timepoints')

            return false;
        }
        else if (txtval <= 1) {
            $(id).parent().next().remove();
        }
        else {
            var html;
            $(id).parent().next().remove();

            html = ' <div class="col-md-4 form-group">'
            for (var i = 0; i < txtval; i++) {
                html += '<input type=text class="clsTimepoints" id=txttime' + i + ' ' + ' placeholder="Timepoint name" value="" required/>';
            }
            html += '</div>'
            $(id).parent().after(html);

            return true;
        }

    }
</script>
<script>
    $("#btnConfigure").click(function () {

        var alertmsg;
        var breakout = false;
        var isChecked = false;
        var ary = new Array();
        var Protocol = $("#Protocol :selected").val();
        debugger;
        if (Protocol =="")
        {
            alert("Please select atleast one protocol");
            return false;
        }
        $(".chk:checked").each(function () {
            isChecked = true;
            var timepoint = new Array();
            if ($(this).parent().find(".clsTPCount").val() == ""||$(this).parent().find(".clsTPCount").val() == 0) {
                alertmsg = "At least one timepoint required for configure";
                breakout = true;
                return false;
            }
            else if ($(this).parent().find(".clsTPCount").val() > 1) {

                $(this).parent().find(".clsTimepoints").each(function () {
                    if ($(this).val() != "") {
                        timepoint.push($(this).val());
                    }
                    else {
                        alertmsg = "Please enter time point name";
                        breakout = true;
                        return false;
                    }
                });
            }
            else if ($(this).parent().find(".clsTPCount").val() == 1)
            {
                $(this).parent().find(".clsTimepoints").each(function () {
                        timepoint.push($(this).val());
                });
            }

            ary.push({ ID: $(this).attr("value"), _isChecked: $(this).is(":checked"), StrArray: timepoint, Protocol_ID: Protocol });

        });
        if (!isChecked)
        {
            alert("Please select atleast one form");
            return false;
        }
        if (breakout) { alert(alertmsg); return false; }
        var data = {
            bo: ary
        }

        $.post("/Configuration/Protocol_Form_Config", data, function (data) {
            if (data.Message == "Success")
            {
                alert("Configured Successfully");
            }
            else {
                alert("Invalid Operation");
            }
        });
        //var protocol = $("#Protocol :selected").val();
        //$.ajax({
        //    type: "POST",
        //    contentType: "application/json; charset=utf-8",
        //    url: "/Configuration/Protocol_Form_Config",
        //    data: data1,
        //    success: function (result) {
        //        //do somthing here
        //    }
        //});
    });

</script>
<script>
    function AllowOnlyNumbers(e) {

        e = (e) ? e : window.event;
        var key = null;
        var charsKeys = [
            97, // a  Ctrl + a Select All
            65, // A Ctrl + A Select All
            99, // c Ctrl + c Copy
            67, // C Ctrl + C Copy
            118, // v Ctrl + v paste
            86, // V Ctrl + V paste
            115, // s Ctrl + s save
            83, // S Ctrl + S save
            112, // p Ctrl + p print
            80 // P Ctrl + P print
        ];

        var specialKeys = [
        8, // backspace
        9, // tab
        27, // escape
        13, // enter
        35, // Home & shiftKey +  #
        36, // End & shiftKey + $
        37, // left arrow &  shiftKey + %
        39, //right arrow & '
        46, // delete & .
        45 //Ins &  -
        ];

        key = e.keyCode ? e.keyCode : e.which ? e.which : e.charCode;

        //console.log("e.charCode: " + e.charCode + ", " + "e.which: " + e.which + ", " + "e.keyCode: " + e.keyCode);
        //console.log(String.fromCharCode(key));

        // check if pressed key is not number
        if (key && key < 48 || key > 57) {

            //Allow: Ctrl + char for action save, print, copy, ...etc
            if ((e.ctrlKey && charsKeys.indexOf(key) != -1) ||
                //Fix Issue: f1 : f12 Or Ctrl + f1 : f12, in Firefox browser
                (navigator.userAgent.indexOf("Firefox") != -1 && ((e.ctrlKey && e.keyCode && e.keyCode > 0 && key >= 112 && key <= 123) || (e.keyCode && e.keyCode > 0 && key && key >= 112 && key <= 123)))) {
                return true
            }
                // Allow: Special Keys
            else if (specialKeys.indexOf(key) != -1) {
                //Fix Issue: right arrow & Delete & ins in FireFox
                if ((key == 39 || key == 45 || key == 46)) {
                    return (navigator.userAgent.indexOf("Firefox") != -1 && e.keyCode != undefined && e.keyCode > 0);
                }
                    //DisAllow : "#" & "$" & "%"
                else if (e.shiftKey && (key == 35 || key == 36 || key == 37)) {
                    return false;
                }
                else {
                    return true;
                }
            }
            else {
                return false;
            }
        }
        else {
            return true;
        }
    }
</script>